import sharp from "sharp";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { writeFileSync } from "node:fs";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "../src/assets");
const heroes = [
  { name: "hero-cricket", file: "hero-cricket.png" },
  { name: "hero-rugby-match", file: "hero-rugby-match.jpg" },
  { name: "hero-rugby-floodlights", file: "hero-rugby-floodlights.jpg" },
  { name: "hero-one-club-many-sports", file: "hero-one-club-many-sports.jpg" },
  { name: "hero-clubhouse-summer", file: "hero-clubhouse-summer.png" },
  { name: "hero-clubhouse-golden-hour", file: "hero-clubhouse-golden-hour.png" },
];

const widths = [640, 1024, 1440, 1920];

for (const hero of heroes) {
  const src = resolve(outDir, hero.file);
  for (const w of widths) {
    const out = resolve(outDir, `${hero.name}-${w}.webp`);
    await sharp(src)
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: 72 })
      .toFile(out);
    console.log("wrote", out);
  }
}

// Tiny blur-up placeholder as an inline data URI (heavily compressed).
const blurBuf = await sharp(resolve(outDir, heroes[0].file))
  .resize({ width: 20 })
  .webp({ quality: 30 })
  .toBuffer();
const dataUri = `data:image/webp;base64,${blurBuf.toString("base64")}`;
writeFileSync(
  resolve(outDir, "hero-blur.js"),
  `// Auto-generated by scripts/optimize-hero.mjs\nexport const heroBlur = "${dataUri}";\n`
);
console.log("wrote hero-blur.js (", blurBuf.length, "bytes )");
