import sharp from "sharp";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { writeFileSync } from "node:fs";

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, "../src/assets/rectory-field-concept.png");
const outDir = resolve(here, "../src/assets");

const widths = [640, 1024, 1440, 1920];

for (const w of widths) {
  const out = resolve(outDir, `rectory-field-${w}.webp`);
  await sharp(src)
    .resize({ width: w, withoutEnlargement: true })
    .webp({ quality: 72 })
    .toFile(out);
  console.log("wrote", out);
}

// Tiny blur-up placeholder as an inline data URI (heavily compressed).
const blurBuf = await sharp(src)
  .resize({ width: 20 })
  .webp({ quality: 30 })
  .toBuffer();
const dataUri = `data:image/webp;base64,${blurBuf.toString("base64")}`;
writeFileSync(
  resolve(outDir, "hero-blur.js"),
  `// Auto-generated by scripts/optimize-hero.mjs\nexport const heroBlur = "${dataUri}";\n`
);
console.log("wrote hero-blur.js (", blurBuf.length, "bytes )");
